"""add subject_contents table

Revision ID: 48a57143bcd4
Revises: add_subject_id_sessions
Create Date: 2025-11-19 11:52:06.333072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a57143bcd4'
down_revision = 'add_subject_id_sessions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sessions_subject_id', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('fk_sessions_subject_id', 'sessions', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###



